services:
    prueba_ingreso:
        container_name: ${APP_SERVICE}
        command: >
            sh -c "npm run serve"
        build: 
          context: .
          dockerfile: dockerfile
        image: node:20.0.0
        environment:
            HOST: "0.0.0.0"
            PORT: ${APP_PORT}
        ports:
            - '${APP_PORT}:${APP_PORT}'
        volumes:
            - '.:/var/www/html'
        working_dir: /var/www/html
        networks:
            - linktic
networks:
    linktic:
        name: linktic
        driver: bridge